export const ships = [
    { name: '100i', slug: '100i' },
    { name: '125a', slug: '125a' },
    { name: '135c', slug: '135c' },
    { name: '300i', slug: '300i' },
    { name: '315p', slug: '315p' },
    { name: '325a', slug: '325a' },
    { name: '350r', slug: '350r' },
    { name: '400i', slug: '400i' },
    { name: '600i Executive Edition', slug: '600i-executive-edition' },
    { name: '600i Explorer', slug: '600i-explorer' },
    { name: '600i Touring', slug: '600i-touring' },
    { name: '85x', slug: '85x' },
    { name: '890 Jump', slug: '890-jump' },
    { name: 'A1 Spirit', slug: 'a1-spirit' },
    { name: 'A2 Hercules', slug: 'a2-hercules' },
    { name: 'Apollo Medivac', slug: 'apollo-medivac' },
    { name: 'Apollo Triage', slug: 'apollo-triage' },
    { name: 'Ares Inferno', slug: 'ares-inferno' },
    { name: 'Ares Ion', slug: 'ares-ion' },
    { name: 'Arrastra', slug: 'arrastra' },
    { name: 'Arrow', slug: 'arrow' },
    { name: 'Aurora CL', slug: 'aurora-cl' },
    { name: 'Aurora ES', slug: 'aurora-es' },
    { name: 'Aurora LN', slug: 'aurora-ln' },
    { name: 'Aurora LX', slug: 'aurora-lx' },
    { name: 'Aurora MR', slug: 'aurora-mr' },
    { name: 'Avenger Stalker', slug: 'avenger-stalker' },
    { name: 'Avenger Titan', slug: 'avenger-titan' },
    { name: 'Avenger Titan Renegade', slug: 'avenger-titan-renegade' },
    { name: 'Avenger Warlock', slug: 'avenger-warlock' },
    { name: 'Ballista', slug: 'ballista' },
    { name: 'Blade', slug: 'blade' },
    { name: 'Buccaneer', slug: 'buccaneer' },
    { name: 'C1 Spirit', slug: 'c1-spirit' },
    { name: 'C2 Hercules', slug: 'c2-hercules' },
    { name: 'C8 Pisces', slug: 'c8-pisces' },
    { name: 'C8R Pisces', slug: 'c8r-pisces' },
    { name: 'C8X Pisces Expedition', slug: 'c8x-pisces-expedition' },
    { name: 'Carrack', slug: 'carrack' },
    { name: 'Caterpillar', slug: 'caterpillar' },
    { name: 'Centurion', slug: 'centurion' },
    { name: 'Constellation Andromeda', slug: 'constellation-andromeda' },
    { name: 'Constellation Aquila', slug: 'constellation-aquila' },
    { name: 'Constellation Phoenix', slug: 'constellation-phoenix' },
    { name: 'Constellation Taurus', slug: 'constellation-taurus' },
    { name: 'Corsair', slug: 'corsair' },
    { name: 'Crucible', slug: 'crucible' },
    { name: 'Cutlass Black', slug: 'cutlass-black' },
    { name: 'Cutlass Blue', slug: 'cutlass-blue' },
    { name: 'Cutlass Red', slug: 'cutlass-red' },
    { name: 'Cutlass Steel', slug: 'cutlass-steel' },
    { name: 'Cutter', slug: 'cutter' },
    { name: 'Cutter Rambler', slug: 'cutter-rambler' },
    { name: 'Cutter Scout', slug: 'cutter-scout' },
    { name: 'Cyclone', slug: 'cyclone' },
    { name: 'Cyclone AA', slug: 'cyclone-aa' },
    { name: 'Cyclone MT', slug: 'cyclone-mt' },
    { name: 'Cyclone RC', slug: 'cyclone-rc' },
    { name: 'Cyclone RN', slug: 'cyclone-rn' },
    { name: 'Cyclone TR', slug: 'cyclone-tr' },
    { name: 'Defender', slug: 'defender' },
    { name: 'Dragonfly Black', slug: 'dragonfly-black' },
    { name: 'Dragonfly Starkitten Edition', slug: 'dragonfly-starkitten-edition' },
    { name: 'Dragonfly Yellowjacket', slug: 'dragonfly-yellowjacket' },
    { name: 'E1 Spirit', slug: 'e1-spirit' },
    { name: 'Eclipse', slug: 'eclipse' },
    { name: 'Endeavor', slug: 'endeavor' },
    { name: 'Expanse', slug: 'expanse' },
    { name: 'F7A Hornet Mk I', slug: 'f7a-hornet-mk-i' },
    { name: 'F7A Hornet Mk II', slug: 'f7a-hornet-mk-ii' },
    { name: 'F7C Hornet Mk I', slug: 'f7c-hornet-mk-i' },
    { name: 'F7C Hornet Mk II', slug: 'f7c-hornet-mk-ii' },
    { name: 'F7C Hornet Wildfire Mk I', slug: 'f7c-hornet-wildfire-mk-i' },
    { name: 'F7C-M Super Hornet Heartseeker Mk I', slug: 'f7c-m-super-hornet-heartseeker-mk-i' },
    { name: 'F7C-M Super Hornet Mk I', slug: 'f7c-m-super-hornet-mk-i' },
    { name: 'F7C-R Hornet Tracker Mk I', slug: 'f7c-r-hornet-tracker-mk-i' },
    { name: 'F7C-S Hornet Ghost Mk I', slug: 'f7c-s-hornet-ghost-mk-i' },
    { name: 'F8C Lightning', slug: 'f8c-lightning' },
    { name: 'F8C Lightning Executive Edition', slug: 'f8c-lightning-executive-edition' },
    { name: 'Freelancer', slug: 'freelancer' },
    { name: 'Freelancer DUR', slug: 'freelancer-dur' },
    { name: 'Freelancer MAX', slug: 'freelancer-max' },
    { name: 'Freelancer MIS', slug: 'freelancer-mis' },
    { name: 'Fury', slug: 'fury' },
    { name: 'Fury LX', slug: 'fury-lx' },
    { name: 'Fury MX', slug: 'fury-mx' },
    { name: 'G12', slug: 'g12' },
    { name: 'G12A', slug: 'g12a' },
    { name: 'G12R', slug: 'g12r' },
    { name: 'Galaxy', slug: 'galaxy' },
    { name: 'Genesis', slug: 'genesis' },
    { name: 'Geotack Planetary Beacon', slug: 'geotack-planetary-beacon' },
    { name: 'Geotack X Planetary Beacon', slug: 'geotack-x-planetary-beacon' },
    { name: 'Gladiator', slug: 'gladiator' },
    { name: 'Gladius', slug: 'gladius' },
    { name: 'Gladius Valiant', slug: 'gladius-valiant' },
    { name: 'Glaive', slug: 'glaive' },
    { name: 'Hammerhead', slug: 'hammerhead' },
    { name: 'Hawk', slug: 'hawk' },
    { name: 'Herald', slug: 'herald' },
    { name: 'Hoverquad', slug: 'hoverquad' },
    { name: 'Hull A', slug: 'hull-a' },
    { name: 'Hull B', slug: 'hull-b' },
    { name: 'Hull C', slug: 'hull-c' },
    { name: 'Hull D', slug: 'hull-d' },
    { name: 'Hull E', slug: 'hull-e' },
    { name: 'Hurricane', slug: 'hurricane' },
    { name: 'Idris M', slug: 'idris-m' },
    { name: 'Idris P', slug: 'idris-p' },
    { name: 'Ironclad', slug: 'ironclad' },
    { name: 'Ironclad Assault', slug: 'ironclad-assault' },
    { name: 'Javelin', slug: 'javelin' },
    { name: 'Khartu-Al', slug: 'khartu-al' },
    { name: 'Kraken', slug: 'kraken' },
    { name: 'Kraken Privateer', slug: 'kraken-privateer' },
    { name: 'Legionnaire', slug: 'legionnaire' },
    { name: 'Liberator', slug: 'liberator' },
    { name: 'Lynx', slug: 'lynx' },
    { name: 'M2 Hercules', slug: 'm2-hercules' },
    { name: 'M50', slug: 'm50' },
    { name: 'Mantis', slug: 'mantis' },
    { name: 'Merchantman', slug: 'merchantman' },
    { name: 'Mercury Star Runner', slug: 'mercury-star-runner' },
    { name: 'Mole', slug: 'mole' },
    { name: 'MPUV Cargo', slug: 'mpuv-cargo' },
    { name: 'MPUV Personnel', slug: 'mpuv-personnel' },
    { name: 'MPUV Tractor', slug: 'mpuv-tractor' },
    { name: 'Mule', slug: 'mule' },
    { name: 'Mustang Alpha', slug: 'mustang-alpha' },
    { name: 'Mustang Beta', slug: 'mustang-beta' },
    { name: 'Mustang Delta', slug: 'mustang-delta' },
    { name: 'Mustang Gamma', slug: 'mustang-gamma' },
    { name: 'Mustang Omega', slug: 'mustang-omega' },
    { name: 'Nautilus', slug: 'nautilus' },
    { name: 'Nomad', slug: 'nomad' },
    { name: 'Nova', slug: 'nova' },
    { name: 'Nox', slug: 'nox' },
    { name: 'Nox Kue', slug: 'nox-kue' },
    { name: 'Odyssey', slug: 'odyssey' },
    { name: 'Orion', slug: 'orion' },
    { name: 'P-52 Merlin', slug: 'p-52-merlin' },
    { name: 'P-72 Archimedes', slug: 'p-72-archimedes' },
    { name: 'Perseus', slug: 'perseus' },
    { name: 'Pioneer', slug: 'pioneer' },
    { name: 'Pirate Gladius', slug: 'pirate-gladius' },
    { name: 'Polaris', slug: 'polaris' },
    { name: 'Prospector', slug: 'prospector' },
    { name: 'Prowler', slug: 'prowler' },
    { name: 'PTV', slug: 'ptv' },
    { name: 'Pulse', slug: 'pulse' },
    { name: 'Pulse LX', slug: 'pulse-lx' },
    { name: 'Raft', slug: 'raft' },
    { name: 'Railen', slug: 'railen' },
    { name: 'Ranger CV', slug: 'ranger-cv' },
    { name: 'Ranger RC', slug: 'ranger-rc' },
    { name: 'Ranger TR', slug: 'ranger-tr' },
    { name: 'Razor', slug: 'razor' },
    { name: 'Razor EX', slug: 'razor-ex' },
    { name: 'Razor LX', slug: 'razor-lx' },
    { name: 'Reclaimer', slug: 'reclaimer' },
    { name: 'Redeemer', slug: 'redeemer' },
    { name: 'Reliant Kore', slug: 'reliant-kore' },
    { name: 'Reliant Mako', slug: 'reliant-mako' },
    { name: 'Reliant Sen', slug: 'reliant-sen' },
    { name: 'Reliant Tana', slug: 'reliant-tana' },
    { name: 'Retaliator', slug: 'retaliator' },
    { name: 'Retaliator Bomber', slug: 'retaliator-bomber' },
    { name: 'ROC', slug: 'roc' },
    { name: 'ROC DS', slug: 'roc-ds' },
    { name: 'Sabre', slug: 'sabre' },
    { name: 'Sabre Comet', slug: 'sabre-comet' },
    { name: 'Sabre Firebird', slug: 'sabre-firebird' },
    { name: 'Sabre Raven', slug: 'sabre-raven' },
    { name: 'San\'tok.yāi', slug: 'san-tok-yai' },
    { name: 'Scorpius', slug: 'scorpius' },
    { name: 'Scorpius Antares', slug: 'scorpius-antares' },
    { name: 'Scythe', slug: 'scythe' },
    { name: 'Spartan', slug: 'spartan' },
    { name: 'SRV', slug: 'srv' },
    { name: 'Starfarer', slug: 'starfarer' },
    { name: 'Starfarer Gemini', slug: 'starfarer-gemini' },
    { name: 'Storm', slug: 'storm' },
    { name: 'Storm AA', slug: 'storm-aa' },
    { name: 'STV', slug: 'stv' },
    { name: 'Syulen', slug: 'syulen' },
    { name: 'Talon', slug: 'talon' },
    { name: 'Talon Shrike', slug: 'talon-shrike' },
    { name: 'Terrapin', slug: 'terrapin' },
    { name: 'Ursa', slug: 'ursa' },
    { name: 'Ursa Fortuna', slug: 'ursa-fortuna' },
    { name: 'Ursa Medivac', slug: 'ursa-medivac' },
    { name: 'Valkyrie', slug: 'valkyrie' },
    { name: 'Vanguard Harbinger', slug: 'vanguard-harbinger' },
    { name: 'Vanguard Hoplite', slug: 'vanguard-hoplite' },
    { name: 'Vanguard Sentinel', slug: 'vanguard-sentinel' },
    { name: 'Vanguard Warden', slug: 'vanguard-warden' },
    { name: 'Vulcan', slug: 'vulcan' },
    { name: 'Vulture', slug: 'vulture' },
    { name: 'X1', slug: 'x1' },
    { name: 'X1 Force', slug: 'x1-force' },
    { name: 'X1 Velocity', slug: 'x1-velocity' },
    { name: 'Zeus Mk II CL', slug: 'zeus-mk-ii-cl' },
    { name: 'Zeus Mk II ES', slug: 'zeus-mk-ii-es' },
    { name: 'Zeus Mk II MR', slug: 'zeus-mk-ii-mr' },
    ]